#!/usr/bin/python3
"""
Module that factorize composite numbers 
into a product of two smaller numbers.
"""

from sys import argv
from math import sqrt


def factors():
    with open(sys.argv[1]) as x:
        for cn in x:
            num = int(cn)
           if cn % 2 == 0:
                  


factors()
