#!/usr/bin/python3
"""
Module that factorize composite numbers 
into a product of two smaller numbers.
"""

from sys import argv
from math import sqrt


def factors():
    with open(argv[1]) as x:
        for cn in x:
            cn = int(cn)
           if cn % 2 == 0:
               print("{}={}*{}".format(cn, cn // 2, 2))
               continue
           y = 3
           while y < cn // 2:
               if cn % y == 0:
                   print("{}={}*{}".format(cn, cn // y, y))
                   break
               y = y + 2
            if y == (cn // 2) + 1:
                print("{}={}*{}".format(cn, cn, 1)


factors()
