#!/usr/bin/python3
import sys


def factors():
    """
    function factors to search file to convert number and format n=p*q
    """
    try:
        revfile = sys.argv[1]
        with open(revfile) as f:
            for n in f:
                n = int(n)
                if n % 2 == 0:
                        print("{}={}*{}".format(n, n // 2, 2))
                        continue
                i = 3
                while i < n // 2:
                    if n % i == 0:
                        print("{}={}*{}".format(n, n // i, i))
                        break
                    i = i + 2
                if i == (n // 2) + 1:
                    print("{}={}*{}".format(n, n, 1))
    except (IndexError):
        pass


# autostart
factors()